name: Package addon

on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

permissions:
  actions: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Run Packager
        uses: BigWigsMods/packager@master
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}


